channels:
  - conda-forge
  - dharpa

host_requirements:
  - pip
  - python
  - setuptools<=63
  - setuptools_scm

test:
  imports:
    - kiara_plugin.dh_tagung_2023
  source_files:
    - tests
    - examples
  commands:
    - kiara module list
